/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 24 19:13:33 GMT 2023
 */

package org.jsoup;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.HttpStatusException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HttpStatusException_ESTest extends HttpStatusException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HttpStatusException httpStatusException0 = new HttpStatusException("org.jsoup.HttpStatusException", 597, "org.jsoup.HttpStatusException");
      String string0 = httpStatusException0.toString();
      assertEquals("org.evosuite.runtime.mock.java.lang.MockThrowable: org.jsoup.HttpStatusException. Status=597, URL=org.jsoup.HttpStatusException", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HttpStatusException httpStatusException0 = new HttpStatusException("org.jsoup.HttpStatusException", 597, "org.jsoup.HttpStatusException");
      int int0 = httpStatusException0.getStatusCode();
      assertEquals(597, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      HttpStatusException httpStatusException0 = new HttpStatusException("org.jsoup.HttpStatusException", 597, "org.jsoup.HttpStatusException");
      String string0 = httpStatusException0.getUrl();
      assertEquals("org.jsoup.HttpStatusException", string0);
  }
}
