/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 24 19:12:50 GMT 2023
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.DocumentType;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DocumentType_ESTest extends DocumentType_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DocumentType documentType0 = new DocumentType("vskCYYPT:($1{`P_U", "", "");
      StringBuilder stringBuilder0 = new StringBuilder("PUBLIC");
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      documentType0.outerHtmlHead(stringBuilder0, 0, document_OutputSettings0);
      assertEquals("PUBLIC<!doctype vskCYYPT:($1{`P_U>", stringBuilder0.toString());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DocumentType documentType0 = new DocumentType("", "G", "", "G", "");
      StringBuffer stringBuffer0 = new StringBuffer("");
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      documentType0.outerHtmlHead(stringBuffer0, 1869, document_OutputSettings0);
      assertEquals(16, stringBuffer0.length());
      assertEquals("<!DOCTYPE G \"G\">", stringBuffer0.toString());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DocumentType documentType0 = new DocumentType("\"~H|kfFl2f", "Yg^B", "Yg^B", "\"~H|kfFl2f", "");
      Document.OutputSettings document_OutputSettings0 = documentType0.getOutputSettings();
      Document.OutputSettings.Syntax document_OutputSettings_Syntax0 = Document.OutputSettings.Syntax.xml;
      document_OutputSettings0.syntax(document_OutputSettings_Syntax0);
      // Undeclared exception!
      try { 
        documentType0.outerHtmlHead((Appendable) null, 2051, document_OutputSettings0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.nodes.DocumentType", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DocumentType documentType0 = new DocumentType("", "", "G{", (String) null);
      documentType0.setPubSysKey("");
      assertEquals("#doctype", documentType0.nodeName());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DocumentType documentType0 = new DocumentType((String) null, (String) null, (String) null, ".v.W+6(Y<\"g/~", (String) null);
      assertEquals("#doctype", documentType0.nodeName());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      DocumentType documentType0 = new DocumentType("Tm+pgQ9DK7-kmdRML", "Tm+pgQ9DK7-kmdRML", "Tm+pgQ9DK7-kmdRML", "Tm+pgQ9DK7-kmdRML");
      assertEquals("#doctype", documentType0.nodeName());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      DocumentType documentType0 = new DocumentType("", "", "G{", (String) null);
      documentType0.setPubSysKey((String) null);
      assertEquals("#doctype", documentType0.nodeName());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      DocumentType documentType0 = new DocumentType("declare", "declare", "GHq)'+9pu.Z8jzIdDiy");
      assertEquals("#doctype", documentType0.nodeName());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      DocumentType documentType0 = new DocumentType("P!i A5Oj_SK", "name", "P!i A5Oj_SK", "P!i A5Oj_SK", "name");
      StringBuilder stringBuilder0 = new StringBuilder("bd|w]=dF?W:`,");
      documentType0.outerHtml((Appendable) stringBuilder0);
      assertEquals("bd|w]=dF?W:`,<!DOCTYPE P!i A5Oj_SK name \"P!i A5Oj_SK\" \"P!i A5Oj_SK\">", stringBuilder0.toString());
  }
}
