/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 24 18:55:07 GMT 2023
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.Attributes;
import org.jsoup.nodes.XmlDeclaration;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class XmlDeclaration_ESTest extends XmlDeclaration_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("UD>", "UD>", false);
      Attributes attributes0 = xmlDeclaration0.attributes();
      attributes0.put("+b~b]N<(", true);
      String string0 = xmlDeclaration0.toString();
      assertEquals("<?UD> +b~b]N<(?>", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("n=?#v3", false);
      String string0 = xmlDeclaration0.getWholeDeclaration();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("", "", true);
      assertEquals("#declaration", xmlDeclaration0.nodeName());
      
      String string0 = xmlDeclaration0.toString();
      assertEquals("<!!>", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("", "", false);
      xmlDeclaration0.name();
      assertEquals("#declaration", xmlDeclaration0.nodeName());
  }
}
