/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 24 18:51:51 GMT 2023
 */

package org.jsoup.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.parser.ParseError;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ParseError_ESTest extends ParseError_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ParseError parseError0 = new ParseError((-1), "");
      String string0 = parseError0.toString();
      assertEquals("-1: ", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Object[] objectArray0 = new Object[6];
      ParseError parseError0 = new ParseError(0, "3j^WN", objectArray0);
      assertEquals(0, parseError0.getPosition());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ParseError parseError0 = new ParseError((-1), "");
      parseError0.getErrorMessage();
      assertEquals((-1), parseError0.getPosition());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ParseError parseError0 = new ParseError((-1), "");
      int int0 = parseError0.getPosition();
      assertEquals((-1), int0);
  }
}
